---
- name: Check node ready
  shell: kubectl get no -o json
  register: kubectl_get_node
  until: kubectl_get_node.stdout | from_json | json_query('items[*].status.conditions[?type==`Ready`].status') | unique == [["True"]]
  retries: 5
  delay: 15
  when: "inventory_hostname == groups['kube_masters'][0]"
